# Example PathoLens pipeline configuration
# Copy this file and edit values to configure the pipeline. The Python
# dataclasses in src/pipeline/config.py just validate these settings at runtime.
# Paths are resolved relative to the project root / current working directory.

[Paths]
# ClinVar variant_summary.txt(.gz)
clinvar = "data/raw/variant_summary.txt.gz"
# Reference FASTA (GRCh38)
fasta = "data/raw/GCF_000001405.40_GRCh38.p14_genomic.fna"
# Gene Ontology gene embedding archive (npz)
go = "data/processed/go_n2v_genes.npz"
# Where all derived artifacts will be written
artifacts = "artifacts/missense"

[DNA]
model_id = "InstaDeepAI/nucleotide-transformer-500m-1000g"
window = 128
max_length = 384
batch_size = 16
force_windows = false
force_embeddings = false

[Protein]
model_id = "facebook/esm2_t12_35M_UR50D"
batch_size = 8
# ``window`` is the target length (residues) for the centered protein slice
window = 127
max_length = 2048
vep_cache_dir = "~/vep_cache"
vep_fasta_relpath = "homo_sapiens/115_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz"
image = "ensemblorg/ensembl-vep"
# Set to false to run a local VEP installation instead of Docker
use_docker = true
chunk_size = 2500
jobs = 18
vep_fork = 0
force_embeddings = false
force_vep = false

[GO]
npz = "data/processed/go_n2v_genes.npz"
normalize = false
uppercase_keys = true

[LLM]
enabled = true
out_dir = "artifacts/missense/qwen3"
model_id = "Qwen/Qwen3-4B-Instruct-2507"
epochs = 1
max_len = 256
per_device_bs = 16
grad_accum = 8
lr = 0.0003
seed = 42
num_workers = 0
prefetch_factor = 2
persistent_workers = false
pin_memory = true
group_by_length = false
drop_last = true
balanced_sampling = true
n_cond_tokens = 12  # total virtual tokens across DNA/Protein/GO
go_tokens = 1       # allocate 1 token for Gene Ontology embeddings
conv_dim = 256
conv_layers = 3
prompt_dropout_prob = 0.3

[Run]
# Location for the manifest JSON that summarises caches
manifest = "artifacts/missense/pipeline_manifest.json"
write_manifest = true
# Filter ClinVar variants by VEP most_severe_consequence before caching (optional)
# filter_most_severe_consequence = ["stop_gained", "missense_variant"]
filter_most_severe_consequence = ["missense_variant"]
force_splits = false
force_dna_windows = false
force_dna_embeddings = false
force_protein_embeddings = false
# Optional global device override; "auto" uses util.get_device()
device = "auto"
